# Generated by Django 3.0.8 on 2020-08-27 02:11

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to=store.models.product_image_file_path),
        ),
    ]
