# Generated by Django 3.0.8 on 2020-08-31 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20200829_0120'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='country',
            field=models.CharField(default='New Zealand', max_length=200),
            preserve_default=False,
        ),
    ]
